version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ibge-api-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - ibge-network
    depends_on:
      - redis

  nginx:
    image: nginx:alpine
    container_name: ibge-api-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - ibge-network
    depends_on:
      - app

  redis:
    image: redis:alpine
    container_name: ibge-api-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - ibge-network

networks:
  ibge-network:
    driver: bridge
